### ISSUE TITLE
Definition names containing spaces are incorrectly rejected

### ISSUE THREAD

**Issue by abingham** [Parquery/swagger-to#120] opened 2020-12-02 08:35 UTC
In this spec the "Base Def" definition has a space in it:
```
basePath: /
consumes:
- application/json
info:
  description: An API
  title: An API
  version: '1.0'
definitions:
  "Base Def":
    properties:
      base_prop:
        type: integer
  Sub:
    allOf:
      - $ref: "#/definitions/Base Def"
      - properties:
          sub_prop:
            type: integer
    type: object
paths:
  /:
    get:
      operationId: get.foo.bar
      responses:
        '200':
          description: Success
produces:
- application/json
swagger: '2.0'
tags:
  - description: Test API
    name: API 
```
This appears to be valid OpenAPI, but `swagger_to_py_client.py` raises an contract violation error:
```
% swagger_to_py_client.py --swagger_path broken.yml --outpath gen                                                                       repos/openapi_elm_client (main ⚡) opabinia
Traceback (most recent call last):
  File "/Users/abingham/.virtualenvs/openapi-elm-client/bin/swagger_to_py_client.py", line 11, in <module>
    load_entry_point('swagger-to', 'console_scripts', 'swagger_to_py_client.py')()
  File "/Users/abingham/repos/swagger-to/swagger_to/bin/swagger_to_py_client.py", line 36, in main
    intermediate_typedefs = swagger_to.intermediate.to_typedefs(swagger=swagger)
  File "/Users/abingham/repos/swagger-to/swagger_to/intermediate.py", line 341, in to_typedefs
    _resolve_substructures(definition=defi, typedefs=typedefs)
  File "/Users/abingham/.virtualenvs/openapi-elm-client/lib/python3.8/site-packages/icontract/_checkers.py", line 396, in wrapper
    result = func(*args, **kwargs)
  File "/Users/abingham/repos/swagger-to/swagger_to/intermediate.py", line 218, in _resolve_substructures
    inter_typedef = _anonymous_or_get_typedef(original_typedef=original_superdef, typedefs=typedefs)
  File "/Users/abingham/repos/swagger-to/swagger_to/intermediate.py", line 251, in _anonymous_or_get_typedef
    definition_name = swagger_to.parse_definition_ref(ref=original_typedef.ref)
  File "/Users/abingham/.virtualenvs/openapi-elm-client/lib/python3.8/site-packages/icontract/_checkers.py", line 403, in wrapper
    _assert_postcondition(contract=contract, resolved_kwargs=resolved_kwargs)
  File "/Users/abingham/.virtualenvs/openapi-elm-client/lib/python3.8/site-packages/icontract/_checkers.py", line 283, in _assert_postcondition
    raise ViolationError(msg)
icontract.errors.ViolationError: File /Users/abingham/repos/swagger-to/swagger_to/__init__.py, line 14 in <module>:
VARIABLE_RE.match(result):
VARIABLE_RE was re.compile('^[a-zA-Z0-9_]+$')
VARIABLE_RE.match(result) was None
result was 'Base Def'
```

**Comment by abingham** [comment] 2020-12-02 08:42
FWIW, I tried the "obvious" fix of adding whitespace to the allowed characters in the regex `swagger_to.VARIABLE_RE`. While this does allow swagger-to to produce output, it has some problems. In particular, the Python class produced for "Base Def" looks like this:
```
class Base:
    def __init__(
            self,
            base_prop: Optional[int] = None) -> None:
        """Initializes with the given values."""
        self.base_prop = base_prop
```
That is, it's called `Base` rather than `BaseDef` or something more complete. This isn't a total showstopper, but it does seem like a bug.

**Comment by abingham** [comment] 2020-12-02 08:52
Also it looks like "-" should be allowed.

**Comment by abingham** [comment] 2020-12-02 08:54
I further explored modifying the relevant regex. When I modify it to allow both whitespace and hyphens, I see that definition names like "JSON-LD object" result in generated Python code like `if exp == JSON-LD object:` which is invalid Python code. Taken together with my earlier note, it seems you'll need to find some robust means of producing Python identifiers for these kinds of strings.

**Comment by mristin** [comment] 2020-12-02 10:16
Hi @abingham ,
Thanks for all this probing! We have never thought of that many edge cases when we started out :-).

I think this needs to be addressed in a similar way the OperationIDs are handled. The names are split (by dot, hyphen, underscore, space *etc.*) and later converted to the appropriate casing (Capital_snake_case or CamelCase, depending on the language). If the user is careless, it might create naming conflicts (say, you have a type "Some class" and "SomeClass" for which the python client generator will both make "SomeClass"), but that is probably much rarer in practice.

Analogously, this should also be done for the property names *etc.*

Please give me a couple of days till I can get back to this as I will be busy this week with unrelated work stuff.

**Comment by mristin** [comment] 2020-12-06 22:41
Hi @abingham ,
Please give me a couple of more days. I'm currently very busy with another project. Is this something that you need urgently?

**Comment by abingham** [comment] 2020-12-07 08:56
There's no great rush on this from my end. We're slowly exploring the
possibilities of code generation from swagger, and it's not blocking us
right now. And of course I'd never presume to impose some sort of deadline
on someone doing open source development! If you don't get to it, maybe
I'll find time to sort it out myself :)

**Comment by mristin** [comment] 2020-12-15 07:40
Hi @abingham ,
Could you please review the PR #122 and see if it fixes your issue? I abstained from fixing the issue at the intermediate representation level as this might introduce unexpected behaviors throughout all the other generators. The only viable solution is probably to fix it on case-by-case basis.

For example, the schema you posted will still break in Elm client and that would need to be fixed individually. Since I am quite busy at the moment (before Christmas sprints...), I can not fix all of them, so please let me know which generators are relevant for you.

**Comment by abingham** [comment] 2020-12-15 07:54
Hi @mristin,
#122 does seem to address the issues with the parsing and Python generation. I see some oddness in the generated Python, e.g.:
```
    if exp == JSONLDObject:
        return j_s_o_n_l_d_object_from_obj(obj, path=path)
```
But this is at least valid Python.

I agree that each generator will need to deal with these kinds of names separately. But I'm not sure that it's a problem for existing users. That is, if someone's already using swagger-to for language X, then they must be using names that swagger-to accepts and which work for their generator; allowing more kinds of names in the IR shouldn't break existing code.

FWIW, [here's the Elm client generator I'm working on for my work](https://github.com/abingham/openapi_elm_client). At least for my purposes, it handles all of the necessary names.

**Comment by mristin** [comment] 2020-12-15 08:31
Hi @abingham ,
The odd identifier is a bug, thanks for spotting it!

I changed the IR layer to accept pretty arbitrary names -- would you relax it even more? (See the PR)

**Comment by abingham** [comment] 2020-12-15 08:39
I'd have it accept anything that openapi allows. But I'd distinguish between a) what the IR allows and b) what any particular generator supports, i.e. treat the generators as separate projects. The generators can always catch up as needed, but at least you can make the IR maximally correct.

**Comment by mristin** [comment] 2020-12-15 09:42
I agree. I'll add a pre-condition in IR to make it clearer.

**Comment by mristin** [comment] 2020-12-15 19:09
@abingham I added JSONLD to the special cases. Mind that splitting on camel case is inherently not well-defined (hence we preferred Pascal_case in our specs). I added a longer message to why the parameter and definition references are constrained:
https://github.com/Parquery/swagger-to/pull/122/commits/cecc806d020f1025c5b2801395ef4b68b875671b

Could you please re-review and re-test on your spec?

**Comment by abingham** [comment] 2020-12-15 19:26
Everything looks good here.

**Comment by mristin** [comment] 2020-12-15 19:31
Great, I'll merge it in! I'll try to look at the other issue tomorrow.

**Closed** 2020-12-15 19:32 UTC
